
import json
import os
from pathlib import Path
import pandas as pd

# %%


# make a class to hold the Data Collection details
##.  Collection Name
##.  Summary
##.  Collection ID
##.  Description 
##   Tags
##.    - Theraputic Area
##.    - Data modality
##.  Update Frequence 
##.  Publisher name
##.  Publisher email
##.  Collection image
##.  Data Ecosystem Alpha JSON
##.  Data snapshot
##.  Data dictionary
##.  Sample use cases
##.  External documentation
@dataclass
class DataCollection:
    def __init__(self, name, summary, collection_id, description, tags, update_frequency, publisher_name, publisher_email):
        self.name = name
        self.summary = summary
        self.collection_id = collection_id

        self.description = description
        self.tags = tags
        self.update_frequency = update_frequency
        self.publisher_name = publisher_name
        self.publisher_email = publisher_email

        self.collection_image = None
        self.data_ecosystem_json = None
        self.data_snapshot = None
        self.data_dictionary = None
        self.sample_use_cases = None
        self.external_documentation = None


# %%
# define template pieces from CRN Harmonized Data Collection

collection_name = "ASAP CRN Harmonized Data Collection"
summary = "Diverse and harmonized omics data from global research teams to accelerate discoveries in Parkinson's disease"
collection_id = "asap-crn-harmonized-data-collection"
description = """
ASAP is a global research initiative changing the way science is typically done. By emphasizing collaboration, generation of research-enabling resources, and data sharing, ASAP is accelerating the pace of discovery and informing the path to a cure for Parkinson’s disease. ASAP is managed by the Coalition for Aligning Science and implemented in partnership with The Michael J. Fox Foundation for Parkinson’s Research.

Access a unique portfolio of cutting-edge resources designed to deepen our understanding of Parkinson's disease (PD), generated by the ASAP CRN, an international, multidisciplinary, and multi-institutional network of collaborating teams working to address high-priority research questions. Explore diverse datasets focused on critical knowledge gaps in PD Functional Genomics, Neuro-Immune Interactions, and Circuitry/Brain-Body Interactions

This openly shared collection includes significant resources like:
- The Harmonized Human Postmortem Brain Sequencing Collection (offering standardized transcriptomic data from hundreds of donors).
- The developing ASAP Parkinson Cell Atlas in 5D (PD5D) molecular atlas resource.
Numerous specialized datasets from leading research teams addressing high-priority questions.

Leverage these resources - emerging from a network committed to open science - to accelerate your research, uncover novel mechanisms, and identify potential therapeutic targets for Parkinson's disease.

### Provenance
#### Source of data

- **Transcriptomics**: Single nucleus RNA Sequencing, Single Cell RNA Sequencing, PolyA RNA Sequencing, Bulk RNA Sequencing, Spatial Transcriptomics
- **Clinical Data**: Demographics, Medical History
- **Biosamples**: Postmortem Brain Tissue, Other Tissues / Cells
- **Pathology**: Clinical Pathology Data

#### Cleaning processes
- **Data Harmonization**: Raw data from various research teams is transformed into a standardized format to ensure consistency across the diverse contributing sites.
- **Uniform Alignment**: Sequencing data is uniformly aligned to reference genomes (e.g., GRCh38).
- **Extensive Quality Control (QC)**: Low-quality cells, samples, and data points are filtered out to maintain high data integrity.
- **Protocol Alignment**: Specialized working groups are established to align methodologies across the network, guaranteeing a robust and reliable final data collection.

#### Data Access
To access this data collection, please follow the steps below. Note that all requests require review and approval by the data owner.

The most efficient way to gain access is to submit a request directly through the official ASAP CRN platform:

**Navigate to the Portal**: Visit the (ASAP CRN Cloud website)[ https://cloud.parkinsonsroadmap.org/].
- **Select Your Data**: Locate the specific dataset you wish to access.
- **Submit Request**: Follow the on-screen instructions to submit your data access request.
- **Verification**: Once the ASAP team approves your request, you will receive notification and instructions on how to view the data.

If you click the Request Access button on this page, Verily will email you the exact instructions and links listed above so you can complete your request on the data owner's website.
"""

# tags and update_frequency is a dictionary
tags = {
    "therapeutic_area": "Neurology",
    "data_modality": "Transcriptomics",
}

Update Frequency = {
    "Update frequency": "Other",
    "text": "Rolling Releases"
}

publisher_name = "Aligning Science Across Parkinson's (ASAP) Initiative"
publisher_email = "cloud@parkinsonsroadmap.org"

collection_image = "https://raw.githubusercontent.com/ASAP-CRN/cloud-orchestration/main/docs/img/ASAP_CRN_Logo.png"

data_ecosystem_json = {
  "isFree": true,
  "patientCount": "568+",
  "geographicCoverage": "International",
  "dataModel": "Non-standard (custom)",
  "timeFrame": "2024 - Present",
  "datePublished": "October 21, 2025",
  "metadataLastUpdated": "October 21, 2025",
  "availability": "Public controlled access",
  "availabilityTooltip": "This is the governance type of the data."
}

data_snapshot = """
#### Sample use cases 
- Investigating the function of PD-associated genes and pathways at a molecular and cellular level.
﻿﻿- Mapping PD genetic risk factors onto specific brain cell types and biological processes.
- Understanding the role of neuroinflammation, microglia, astrocytes, and peripheral immune interactions in PD development and progression.
﻿﻿- Analyzing disruptions in neuronal circuits and brain-body communication relevant to PD symptoms and pathology.
- Exploring cell-type-specific changes in the human PD brain using single-cell and spatial omics data from postmortem tissue.
- Creating comprehensive molecular datasets or the Parkinson's brain.
- Identifying and validating novel therapeutic targets emerging from fundamental research into disease mechanisms.

&nbsp; 

### Publications referencing this data collection
A full list of preprints (from Biorxiv and Medrxiv only) associated with ASAP and publication outputs, including both original research reviews from the CRN, can be accessed through the following links:
- ASAP BioRxiv Channel: [Preprints](https://connect.biorxiv.org/relate/content/195) 
- PubMed Collection: [Publications](https://www.ncbi.nlm.nih.gov/myncbi/browse/collection/61351065/) 

&nbsp; 

### Sample queries
- CRN Cloud GitHub: [Here](https://github.com/ASAP-CRN) 
- Getting Started Notebooks: [Here](https://github.com/ASAP-CRN/2025_CRN_CM_Workshop)

"""

external_documentation = """
- [ASAP CRN Cloud](https://cloud.parkinsonsroadmap.org/collections)
"""

# %%
# collect into one dictionary
asap_crn_data_collection = {
    "name": collection_name,
    "summary": summary,
    "collection_id": collection_id,
    "description": description,
    "tags": tags,
    "update_frequency": Update Frequency,
    "publisher_name": publisher_name,
    "publisher_email": publisher_email,
    "collection_image": collection_image,
    "data_ecosystem_json": data_ecosystem_json,
    "data_snapshot": data_snapshot,
    "external_documentation": external_documentation
}

# %%
# print the dictionary in json format
print(json.dumps(asap_crn_data_collection, indent=2))

# %% export to template json file
with open("asap_crn_data_collection_template.json", "w") as f:
    json.dump(asap_crn_data_collection, f, indent=2)


#%%
# ############
# now do the same thing for workspaces
# make a dataclass for workspaces
#   Workspace name
#.  Summary
#.  Workspace id
#.  Description 

workspace_name = "ASAP CRN Reference Workspace (v5.0-dev)"
workspace_summary = "Reference workspace to enable quickly getting started with the ASAP CRN Cloud."
workspace_id = "asap-crn-reference-workspace-v5-0-dev"
workspace_description = """
![ASAP logo](https://parkinsonsroadmap.org/wp-content/uploads/2020/10/cropped-ASAP_Logo_FullColor.png)

# Getting Started

## Step 1: Duplicate Workspace

To get started with using the data, click on the button in the top-right of the window, and select "Duplicate". Follow the flow to create a copy of this workspace which you can use to begin working with the data.

In your copy of the workspace, navigate to the "Environments" tab and create a cloud environment for running Jupyter notebooks. You'll find example notebooks and also be able to browse and access the data via bucket mounts in the `~/workspace` directory.

Note that you'll need to have set up billing for this. To connect a billing account with Workbench, please see [Setting up pods and billing in Workbench](https://support.workbench.verily.com/docs/technical_reference/admin/billing_setup/) or email workbench-support@verily.com.


## Step 2: Setup Access to Raw Data (Optional)

Follow the instructions provided in [How to Access and Analyze Raw Files in Verily Workbench](./asap-crn-reference-workspace/resources/9099df22-8412-4c7c-adb7-810f261d0820/docs/how-to-access-and-analyze-raw-files-in-verily-workbench.html) to set up access to raw data.

## Step 3: Next Steps

Use sample notebooks to begin exploring data by following the instructions provided in [Workbench Next Steps](./asap-crn-reference-workspace/resources/9099df22-8412-4c7c-adb7-810f261d0820/docs/workbench-next-steps.md).

# Resources

See the [Data Dictionary](https://storage.googleapis.com/asap-public-assets/wayfinding/ASAP-CRN-Cloud-Data-Dictionary.pdf) for an overview of the metadata tables.

In your workspace, select the "Resources" tab above. In the resource tree, you will find:

* Data - Data contained within collections found in CRN Cloud.
  * Multi Cohort Curated Data - Harmonized data collections
    * Cohort_Analysis - Processed data
    * Preprocess - Data generated during the preprocessing step of curation
  * Team Curated Data - Data contributed by individual teams.
    * Cohort_Analysis - Processed data
    * Preprocess - Data generated during the preprocessing step of curation

(Note: Raw data, the data as it was submitted by the CRN teams, is available in ‘Requester Pays’ buckets. Follow the instructions in [How to Access and Analyze Raw Files in Verily Workbench](./asap-crn-reference-workspace/resources/9099df22-8412-4c7c-adb7-810f261d0820/docs/how-to-access-and-analyze-raw-files-in-verily-workbench.html) to access raw data.)

* Documentation
* Sample_Notebooks
  * R - Explore ASAP CRN Data
  * Py3 - Explore ASAP CRN Data
* `ws_file` - Bucket for long-term storage of data, notebooks, and analysis results.

You can browse these resources in the workspace tree and preview documentation and data.

# Contact

For more information or questions regarding ASAP CRN data and the program, please email cloud@parkinsonsroadmap.org.
"""